# Generated by Django 4.2 on 2023-05-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_user_profile_remove_contact_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='inconnu', max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('First_Name', models.CharField(default='inconnu', max_length=100)),
                ('Last_Name', models.CharField(default='inconnu', max_length=100)),
                ('Phone_Number', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.DeleteModel(
            name='User_profile',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-date_added']},
        ),
    ]
