# Generated by Django 4.2 on 2023-05-11 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_user_delete_user_profile_alter_contact_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
